services:
  django:
    build:
      context: ./backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./backend:/app
      - databricks_data:/app/databricks/data
    ports:
      - "8000:8000"
    env_file:
      - ./backend/.env
    restart: always

  tg_bot:
    build:
      context: ./tg_bot
    env_file:
      - ./tg_bot/.env
    restart: always

  cron:
    build:
      context: ./backend
    command: >
      sh -c "while true; do python run_task_lacetti_white.py;
      sleep 3600; done"
    volumes:
      - ./backend:/app
      - databricks_data:/app/databricks/data
    env_file:
      - ./backend/.env
    restart: always
    depends_on:
      - django

  databricks:
    image: python:3.12-slim
    volumes:
      - databricks_data:/app/databricks/data
    working_dir: /app/databricks/data
    command: tail -f /dev/null

volumes:
  databricks_data:
